In [1]:
import pandas as pd

In [12]:
df = pd.read_csv('/data/ds-neuralpriors/derivatives/summary_tsvs/main_models_roi-NPCr_desc-groundtruth_parameters.tsv.gz', sep='\t', index_col=[0,1,2,3,4], header=[0])

In [15]:
df.loc[df['loglikelihood'].isnull()]

Empty DataFrame
Columns: [loglikelihood, cvr2, aic, bic, mu_narrow, mu_wide, sd_narrow, sd_wide, delta_wide_narrow, delta_wide_wide, amplitude_narrow, amplitude_wide, baseline_narrow, baseline_wide, r2]
Index: []

In [16]:
df

                                                                             loglikelihood  \
subject model_label model                                response_fit voxel
1       -1          No tuning (null model)               False        0        -683.927119
                                                                      1        -648.913000
                                                                      2        -524.546526
                                                                      3        -493.602638
                                                                      4        -729.624278
...                                                                                    ...
41       36         Fixed tuning, shared amplitude ratio True         689      -282.834497
                                                                      690      -157.962688
                                                                      691      -296.284329
                                                                      692      -384.525844
                                                                      693      -372.101391

                                                                                 cvr2  \
subject model_label model                                response_fit voxel
1       -1          No tuning (null model)               False        0     -0.006575
                                                                      1     -0.007867
                                                                      2     -0.009274
                                                                      3     -0.009871
                                                                      4     -0.004070
...                                                                               ...
41       36         Fixed tuning, shared amplitude ratio True         689    0.001519
                                                                      690   -0.009964
                                                                      691   -0.008262
                                                                      692   -0.008869
                                                                      693   -0.015471

                                                                                     aic  \
subject model_label model                                response_fit voxel
1       -1          No tuning (null model)               False        0      1371.854238
                                                                      1      1301.825999
                                                                      2      1053.093052
                                                                      3       991.205276
                                                                      4      1463.248556
...                                                                                  ...
41       36         Fixed tuning, shared amplitude ratio True         689            NaN
                                                                      690            NaN
                                                                      691            NaN
                                                                      692            NaN
                                                                      693            NaN

                                                                                     bic  \
subject model_label model                                response_fit voxel
1       -1          No tuning (null model)               False        0      1380.201810
                                                                      1      1310.173572
                                                                      2      1061.440624
                                                                      3       999.552849
                                                                      4      1471.596128
...                                                                                  ...
41       36         Fixed tuning, shared amplitude ratio True         689            NaN
                                                                      690            NaN
                                                                      691            NaN
                                                                      692            NaN
                                                                      693            NaN

                                                                             mu_narrow  \
subject model_label model                                response_fit voxel
1       -1          No tuning (null model)               False        0            NaN
                                                                      1            NaN
                                                                      2            NaN
                                                                      3            NaN
                                                                      4            NaN
...                                                                                ...
41       36         Fixed tuning, shared amplitude ratio True         689    14.034764
                                                                      690     4.635901
                                                                      691    13.497054
                                                                      692     4.048149
                                                                      693     3.549696

                                                                               mu_wide  \
subject model_label model                                response_fit voxel
1       -1          No tuning (null model)               False        0            NaN
                                                                      1            NaN
                                                                      2            NaN
                                                                      3            NaN
                                                                      4            NaN
...                                                                                ...
41       36         Fixed tuning, shared amplitude ratio True         689    14.034764
                                                                      690     4.635901
                                                                      691    13.497054
                                                                      692     4.048149
                                                                      693     3.549696

                                                                             sd_narrow  \
subject model_label model                                response_fit voxel
1       -1          No tuning (null model)               False        0            NaN
                                                                      1            NaN
                                                                      2            NaN
                                                                      3            NaN
                                                                      4            NaN
...                                                                                ...
41       36         Fixed tuning, shared amplitude ratio True         689     0.948954
                                                                      690     0.399879
                                                                      691     0.961226
                                                                      692     0.768567
                                                                      693     1.827475

                                                                              sd_wide  \
subject model_label model                                response_fit voxel
1       -1          No tuning (null model)               False        0           NaN
                                                                      1           NaN
                                                                      2           NaN
                                                                      3           NaN
                                                                      4           NaN
...                                                                               ...
41       36         Fixed tuning, shared amplitude ratio True         689    0.948954
                                                                      690    0.399879
                                                                      691    0.961226
                                                                      692    0.768567
                                                                      693    1.827475

                                                                             delta_wide_narrow  \
subject model_label model                                response_fit voxel
1       -1          No tuning (null model)               False        0                    NaN
                                                                      1                    NaN
                                                                      2                    NaN
                                                                      3                    NaN
                                                                      4                    NaN
...                                                                                        ...
41       36         Fixed tuning, shared amplitude ratio True         689                  1.0
                                                                      690                  1.0
                                                                      691                  1.0
                                                                      692                  1.0
                                                                      693                  1.0

                                                                             delta_wide_wide  \
subject model_label model                                response_fit voxel
1       -1          No tuning (null model)               False        0                  NaN
                                                                      1                  NaN
                                                                      2                  NaN
                                                                      3                  NaN
                                                                      4                  NaN
...                                                                                      ...
41       36         Fixed tuning, shared amplitude ratio True         689                1.0
                                                                      690                1.0
                                                                      691                1.0
                                                                      692                1.0
                                                                      693                1.0

                                                                             amplitude_narrow  \
subject model_label model                                response_fit voxel
1       -1          No tuning (null model)               False        0                   NaN
                                                                      1                   NaN
                                                                      2                   NaN
                                                                      3                   NaN
                                                                      4                   NaN
...                                                                                       ...
41       36         Fixed tuning, shared amplitude ratio True         689            0.512772
                                                                      690            0.656658
                                                                      691            0.410114
                                                                      692            0.465975
                                                                      693            0.299989

                                                                             amplitude_wide  \
subject model_label model                                response_fit voxel
1       -1          No tuning (null model)               False        0                 NaN
                                                                      1                 NaN
                                                                      2                 NaN
                                                                      3                 NaN
                                                                      4                 NaN
...                                                                                     ...
41       36         Fixed tuning, shared amplitude ratio True         689          0.644936
                                                                      690          0.825907
                                                                      691          0.515818
                                                                      692          0.586077
                                                                      693          0.377309

                                                                             baseline_narrow  \
subject model_label model                                response_fit voxel
1       -1          No tuning (null model)               False        0                  NaN
                                                                      1                  NaN
                                                                      2                  NaN
                                                                      3                  NaN
                                                                      4                  NaN
...                                                                                      ...
41       36         Fixed tuning, shared amplitude ratio True         689          -0.148841
                                                                      690           0.277656
                                                                      691          -0.148784
                                                                      692          -0.109130
                                                                      693          -0.128907

                                                                             baseline_wide  \
subject model_label model                                response_fit voxel
1       -1          No tuning (null model)               False        0                NaN
                                                                      1                NaN
                                                                      2                NaN
                                                                      3                NaN
                                                                      4                NaN
...                                                                                    ...
41       36         Fixed tuning, shared amplitude ratio True         689        -0.148841
                                                                      690         0.277656
                                                                      691        -0.148784
                                                                      692        -0.109130
                                                                      693        -0.128907

                                                                                   r2
subject model_label model                                response_fit voxel
1       -1          No tuning (null model)               False        0           NaN
                                                                      1           NaN
                                                                      2           NaN
                                                                      3           NaN
                                                                      4           NaN
...                                                                               ...
41       36         Fixed tuning, shared amplitude ratio True         689    0.025566
                                                                      690    0.005594
                                                                      691    0.016728
                                                                      692    0.014003
                                                                      693    0.004484

[946523 rows x 15 columns]